version: "3.7"
services:
   docker-go:
      image: docker-go
      ports:
         - 8080:8080
      volumes:
         - ./:/go/src
      environment:
         DB_HOST: mysql
         DB_USERNAME: root
         DB_PASSWORD: secret
         DB_NAME: docker-go
         ENVIRONMENT: development
      depends_on: 
         - mysql
   mysql:
      image: mysql:5.7
      volumes:
         - docker-go-mysql-data:/var/lib/mysql
      ports: 
         - 3306:3306
      environment:
         MYSQL_ROOT_PASSWORD: secret
         MYSQL_DATABASE: docker-go

volumes:
   docker-go-mysql-data:
