version: "3.7"
services:
  docker-go:
    image: docker-go
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src
    restart: always
    environment:
      DB_HOST: mssql
      DB_USERNAME: sa
      DB_PASSWORD: Secret123
      DB_NAME: DockerGo
      ENVIRONMENT: development
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - docker-go-mssql-data:/var/opt/mssql/data
    ports:
      - 14331:1433
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Secret123

volumes:
  docker-go-mssql-data:
